apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: password
          name: mysql
          image: mysql/mysql-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE SCHEMA `service-users` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    CREATE SCHEMA `service-aircrafts` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    CREATE SCHEMA `service-requests` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    CREATE SCHEMA `service-parking` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    CREATE SCHEMA `service-billings` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';