apiVersion: v1
kind: Service
metadata:
  name: service-billings
spec:
  selector:
    app: service-billings
  type: NodePort
  ports:
    - name: http
      port: 8085
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-billings
spec:
  selector:
    matchLabels:
      app: service-billings
  replicas: 1
  template:
    metadata:
      labels:
        app: service-billings
    spec:
      containers:
        - name: server
          image: smurfik997/service-billings:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8085

---