apiVersion: v1
kind: Service
metadata:
  name: service-requests
spec:
  selector:
    app: service-requests
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-requests
spec:
  selector:
    matchLabels:
      app: service-requests
  replicas: 1
  template:
    metadata:
      labels:
        app: service-requests
    spec:
      containers:
        - name: server
          image: smurfik997/service-requests:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083

---